ERROR_INVALID_BODY   = 100
ERROR_UNDEFINED_ROLE = 101

ERROR_REQUEST_NOT_FOUND           = 200
ERROR_REQUEST_SESSION_NOT_CREATED = 201
ERROR_REQUEST_ALREADY_ANSWERED    = 202
ERROR_REQUEST_NOT_ANSWERED        = 203