source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo_mapper'
gem 'opentok', '~> 2.2.1'
gem 'hashids'
gem 'urbanairship'
gem 'aescrypt'
gem 'json-schema'
gem 'bcrypt-ruby', :require: 'bcrypt'
gem 'rufus-scheduler'
gem 'activesupport'
gem 'bson_ext'
gem 'mandrill-api'
gem 'tzinfo'
gem 'tzinfo-data'

gem 'event_bus'
group :development do
  gem 'rubocop'
  gem 'rspec-mocks'
  gem 'factory_girl'
  gem 'rspec'
  gem 'shoulda'
  gem 'rest-client'
  gem 'rack-test', require: 'rack/test'
  gem 'guard'
  gem 'guard-rspec'
  gem 'rspec-autotest'
  gem 'timecop'
end

gem 'rake'

gem 'newrelic_rpm'
