source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'opentok'
gem 'mongomapper_id2'
gem 'hashids'
gem 'urbanairship'
gem 'aescrypt'
gem 'json-schema'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'rufus-scheduler'
gem "activesupport"
gem 'bson_ext'

gem 'rspec-mocks'
gem 'factory_girl'
gem 'rspec'
gem 'shoulda'

gem 'rest-client'
gem 'newrelic_rpm'
